apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath_pv
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: localstorage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mongodb